Lesson-4
hawk911/thinknetica-go-core-3 pull request #3
Opened 2022-04-13 05:14 UTC by hawk911

2022-04-14 15:20 UTC, DmitriyVTitov requested changes
Пришлось даже запустить программу:
=== RUN   TestList_Pop
--- FAIL: TestList_Pop (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x68f2bd]

2022-04-14 15:20 UTC, DmitriyVTitov commented on lesson-4/cmd/list.go
> +}
что-то не то
на элемент l.root.next (первый элемент списка) после удаления продолжает ссылаться как минимум второй элемент l.root.next.next.prev

2022-04-15 01:29 UTC, hawk911 commented on lesson-4/cmd/list.go
> +}
Что очень странно. Тесты прошли у меня: 
```
=== RUN   TestNew
    list_test.go:9: 
--- PASS: TestNew (0.00s)
=== RUN   TestList_Push
--- PASS: TestList_Push (0.00s)
=== RUN   TestList_Pop
--- PASS: TestList_Pop (0.00s)
=== RUN   TestList_Reverse
--- PASS: TestList_Reverse (0.00s)
PASS
```

2022-04-18 14:35 UTC, DmitriyVTitov requested changes
Тест же опять не проходит? Зачем сдавать задание, если не срабатывает критерий проверки.
Вам нужно убедиться, что тесты работают, прежде чем присылать ответ.

2022-04-18 14:35 UTC, DmitriyVTitov commented on lesson-4/cmd/list.go
> +	return l
что-то непонятное
1. корень списка не является первым элементом (при добавлении элемент всегда добавляется после root, также работает и String())
2. не нужно "сохранять" переменную при присваивании
`a, b = b, a` сработает без проблем

2022-04-18 15:04 UTC, hawk911 commented on lesson-4/cmd/list.go
> +	return l
Тут у меня тест не проходит. А вот предыдущее решение - там прошли, поэтому у меня и недопонимание - https://github.com/hawk911/thinknetica-go-core-3/pull/3#discussion_r850970128

2022-04-18 15:39 UTC, hawk911 commented on lesson-4/cmd/list.go
> +	//l.root.next, l.root.next.prev = l.root, l.root.next.next
Почему не работает? Хотя судя по выше замечанию (`a, b = b, a`) должно работать.

2022-04-20 08:18 UTC, DmitriyVTitov reviewed
OK

2022-04-20 08:18 UTC, DmitriyVTitov commented on lesson-4/cmd/list.go
> +	//l.root.next, l.root.next.prev = l.root, l.root.next.next
потому что значения перепутаны местами:
`l.root.next, l.root.next.prev = l.root.next.next, l.root`

2022-04-22 01:16 UTC, merged